name: PR Auto Label

on:
  pull_request:
    types: [opened]

jobs:
  label:
    name: Add skip-release label
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add skip-release label
        uses: actions/github-script@60a0d83039f74b59c328d781e62d1b2160834302 # v7.0.1
        with:
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['skip-release']
              });
            } catch (error) {
              core.warning(`Could not add skip-release label: ${error.message}`);
            }
